version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest' 
    container_name: gitlab 
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://0.0.0.0:8993'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8993:8993'
      - '12224:22'
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
networks:
  default:
    name: sonarqube_sonar-network
    external: true
volumes:
  config:
  logs:
  data: